spring:
  profiles:
    active: '@environment@'
  application:
    name: boot-learn
  mvc:
    static-path-pattern: /static/**

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.my.bootlearn.entity
